AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cake Shop SaaS EC2 Instance Template (Free Tier Eligible)'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: The latest Amazon Linux 2 AMI from the Parameter Store

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type (t2.micro is free tier eligible).

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  DBHost:
    Description: RDS endpoint
    Type: String

  DBName:
    Description: Database name
    Type: String
    Default: cakeshop

  DBUser:
    Description: Database user
    Type: String
    Default: admin

  DBPassword:
    Description: Database password
    Type: String
    NoEcho: true

  DBPort:
    Description: Database port
    Type: String
    Default: "3306"

  RedisHost:
    Description: Redis host for caching (optional)
    Type: String
    Default: "none"

  S3Bucket:
    Description: S3 bucket for media storage
    Type: String
    Default: "cakeshop-media-unique"

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP, HTTPS, and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  WebServerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  WebServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WebServerRole

  WebServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref WebServerInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          amazon-linux-extras install -y lamp-mariadb10.2-php7.4 php7.4
          yum install -y httpd git unzip

          # Install PHP extensions
          yum install -y php-gd php-mbstring php-xml php-curl php-zip php-intl php-bcmath php-json php-mysql

          # Install Composer
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

          # Start Apache
          systemctl start httpd
          systemctl enable httpd

          # Clone app
          cd /var/www/html
          git clone https://github.com/Harydhk7/cakeshop-saas.git .

SECRET=$(openssl rand -base64 32)
export APP_SECRET="$SECRET"

cat > /var/www/html/src/app/config/parameters.php << EOF
<?php
return [
    'parameters' => [
        'database_host' => '${DBHost}',
        'database_port' => '${DBPort}',
        'database_name' => '${DBName}',
        'database_user' => '${DBUser}',
        'database_password' => '${DBPassword}',
        'database_prefix' => 'ps_',
        'database_engine' => 'InnoDB',
        'mailer_transport' => 'smtp',
        'mailer_host' => '127.0.0.1',
        'mailer_user' => null,
        'mailer_password' => null,
        'secret' => getenv('APP_SECRET') ?: 'changeme',
        'ps_caching' => 'CacheMemcache',
        'ps_cache_enable' => true,
        'ps_creation_date' => '$(date +%Y-%m-%d)',
        'redis_host' => '${RedisHost}',
        'redis_port' => '6379',
    ]
];
EOF

              ]
          ];
          EOF

          # S3 media configuration
          cat > /var/www/html/src/config/defines.inc.php << EOF
          <?php
          define('_PS_MEDIA_SERVER_1_', 'https://${S3Bucket}.s3.amazonaws.com');
          define('_PS_MEDIA_SERVER_2_', 'https://${S3Bucket}.s3.amazonaws.com');
          define('_PS_MEDIA_SERVER_3_', 'https://${S3Bucket}.s3.amazonaws.com');
          EOF

          # Restart Apache
          systemctl restart httpd

  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref WebServerLaunchConfig
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      AvailabilityZones: !GetAZs 
        Ref: AWS::Region
      Tags:
        - Key: Name
          Value: Cake Shop SaaS Web Server
          PropagateAtLaunch: true

Outputs:
  WebServerSecurityGroup:
    Description: Security group for web servers
    Value: !Ref WebServerSecurityGroup

  AutoScalingGroup:
    Description: Auto Scaling Group containing the web servers
    Value: !Ref WebServerGroup
